PRAGMA foreign_keys = ON;

CREATE TABLE IF NOT EXISTS d_msg_count (
    UID INTEGER PRIMARY KEY NOT NULL,
    numSent INTEGER DEFAULT 1,
    lastSeen timestamp NOT NULL DEFAULT (strftime('%s', 'now'))
) WITHOUT ROWID;

CREATE TABLE IF NOT EXISTS d_quotes (
    ID INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    msg TEXT NOT NULL,
    date TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS joke_count (
    joke TEXT PRIMARY KEY NOT NULL,
    count INTEGER NOT NULL DEFAULT 0
);